version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    restart: unless-stopped
    ports:
      # bind to localhost only for safety
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      # run the setup wizard on first boot (simpler for learning)
      JAVA_OPTS: -Djenkins.install.runSetupWizard=true

volumes:
  jenkins_home:
